name: hydint_env
channels:
  - conda-forge
  - stochasticHydroTools
  - complexfluidsuam

dependencies:
  - python
  - numpy
  - scipy
  - pyvista
  - libMobility
  - pytest
  - pip
  - uammd-structured=*=*double*
  - pyUAMMD
  - pip:  # These are the packages that will be installed with pip
    - matplotlib
    - pyvista
    - icosphere
    - pyVLMP

  