name: hydint_env
channels:
  - conda-forge
  - stochasticHydroTools

dependencies:
  - python
  - numpy
  - scipy
  - pyvista
  - libMobility
  - pytest
  - pip
  - pip:  # These are the packages that will be installed with pip
    - matplotlib
    - pyvista

  